### Get trackers
GET {{host}}/api/trackers
Accept: application/json

### Get trackers by tags
GET {{host}}/api/trackers?tag=app:retrack
Accept: application/json

### Get tracker
GET {{host}}/api/trackers/0190acf7-1821-74c0-8f63-ab3b58a70bd4
Accept: application/json

### Get tracker revisions
GET {{host}}/api/trackers/0190acf7-1821-74c0-8f63-ab3b58a70bd4/revisions
Accept: application/json

### Create tracker (minimal)
POST {{host}}/api/trackers
Content-Type: application/json
Accept: application/json

{
  "name": "GitHub Icon",
  "target": {
    "type": "web:page",
    "extractor": "export async function execute(page, result) { await page.goto('https://retrack.dev'); return result.html(await page.content()); };"
  }
}

### Create tracker
POST {{host}}/api/trackers
Content-Type: application/json
Accept: application/json

{
  "name": "GitHub Icon",
  "url": "https://github.com",
  "target": {
    "type": "web:page",
    "waitFor": {
      "selector": ".octicon-mark-github"
    }
  },
  "config": {
    "revisions": 3,
    "extractor": "return document.querySelector('.octicon-mark-github')?.textContent;",
    "job": {
      "schedule": "0 */2 * * * * *"
    }
  },
  "tags": ["app:retrack"]
}

### Update tracker
PUT {{host}}/api/trackers/0190acf7-1821-74c0-8f63-ab3b58a70bd4
Content-Type: application/json
Accept: application/json

{
  "config": {
    "revisions": 10,
    "extractor": "return document.querySelector('.octicon-mark-github')?.innerHTML;",
    "job": {
      "schedule": "0 */2 * * * * *"
    }
  }
}

### Delete tracker
DELETE {{host}}/api/trackers/0190acdd-6b11-71c0-be14-bfa8c7c4cce3
