### Get status
GET {{web-scraper}}/api/status
Accept: application/json
Content-Type: application/json

### Execute extractor script
POST {{web-scraper}}/api/web_page/execute
Accept: application/json
Content-Type: application/json

{
  "extractor": "data:text/javascript,console.log(process.env);"
}

### Execute extractor script (complex, should fail).
POST {{web-scraper}}/api/web_page/execute
Accept: application/json
Content-Type: application/json

{
  "extractor": "async function execute(context) { const { workerData } = await import('node:worker_threads');console.log(`LEAK: ${JSON.stringify(workerData.wsEndpoint)}`); const page = await context.newPage(); await page.goto('https://google.com'); return await page.evaluate(([x, y]) => Promise.resolve(x * y), [7, 8]); }; export { execute };"
}

### Execute extractor script (complex).
POST {{web-scraper}}/api/web_page/execute
Accept: application/json
Content-Type: application/json

{
  "extractor": "async function execute(context) { const page = await context.newPage(); await page.goto('https://yandex.ru'); return await page.context().browser().contexts().length }; export { execute };"
}

### Execute extractor script (cdp).
POST {{web-scraper}}/api/web_page/execute
Accept: application/json
Content-Type: application/json

{
  "extractor": "async function execute(context) { const page = await context.newPage(); await page.goto('https://google.com'); return JSON.stringify(await (await context.newCDPSession(page)).send('Target.getTargets')); }; export { execute };"
}

### Execute extractor script (cdp).
< {%
  const extractor = `
    async function execute(context, result) {
      const page = await context.newPage();
      const delay = (time) => new Promise((resolve) => setTimeout(resolve, time));
      await delay(5000);
      await page.goto('https://y5l3m6u-demo.webhooks.dev.secutils.dev/');
      await delay(5000);
      /*return result.html(await page.locator('table.overview-table').innerHTML());*/
      return await page.content();
    };
    export { execute };
  `;
  request.variables.set("extractor", extractor.replaceAll('\n', '').trim())
%}
POST {{web-scraper}}/api/web_page/execute
Accept: application/json
Content-Type: application/json

{
  "extractor": "{{extractor}}"
}
