name: Retrack

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Dockerfile'
      - '*.json'
      - '*.md'
      - 'retrack.toml'
      - '.husky/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Build (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      # Always install nightly toolchain for `Rustfmt`.
      - name: Install toolchain ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }} nightly
          rustup override set ${{ matrix.rust }}
          rustup component add clippy
          rustup component add --toolchain nightly rustfmt

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo +nightly fmt --all -- --check

      - name: Test (default features)
        run: cargo test

      - name: Build (default features)
        run: cargo build --release

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
#  ci-control-center:
#    name: Build (Linux)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        name: Checkout
#
#      - name: Set Node.js 20.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 20.x
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build
#        run: npm run build --ws
